@extends('layouts.app')
@section('title', __('ui.profile'))
@section('description', 'Profil, sejarah, visi, misi, dasar hukum, dan petugas Unit Layanan Terpadu Universitas Padjadjaran.')
@section('content')
@php($en = app()->getLocale() === 'en')
<section class="profile-hero"><div class="container profile-hero-grid"><div class="reveal">
    <span class="pill">{{ $en ? 'About ULT Unpad' : 'Tentang ULT Unpad' }}</span>
    <h1>{{ $en ? 'A trusted gateway to' : 'Garda terdepan' }} <em>{{ $en ? 'Unpad services.' : 'pelayanan Unpad.' }}</em></h1>
    <p>{{ $en ? 'Since 2015, ULT Unpad has continued to grow as an integrated, accessible, and user-focused public service gateway.' : 'Sejak 2015, ULT Unpad terus berkembang menjadi pintu pelayanan publik yang terpadu, mudah diakses, dan berorientasi pada kebutuhan pengguna.' }}</p>
    <div class="profile-stats"><div><b>2015</b><span>{{ $en ? 'Established' : 'Mulai berdiri' }}</span></div><div><b>2016</b><span>{{ $en ? 'One Stop Service' : 'Layanan satu pintu' }}</span></div><div><b>PASTI</b><span>{{ $en ? 'Service values' : 'Nilai pelayanan' }}</span></div></div>
</div><div class="profile-hero-image"><img src="{{ asset('images/profil-ult-resepsionis.jpeg') }}" alt="Area resepsionis Unit Layanan Terpadu Unpad"><span>{{ $en ? 'Unit Layanan Terpadu, Universitas Padjadjaran' : 'Unit Layanan Terpadu Universitas Padjadjaran' }}</span></div></div></section>

<nav class="profile-subnav" aria-label="{{ $en ? 'Profile sections' : 'Bagian profil' }}"><div class="container"><a href="#sejarah">{{ $en ? 'History' : 'Sejarah' }}</a><a href="#visi-misi">{{ $en ? 'Vision & Mission' : 'Visi & Misi' }}</a><a href="#pasti">PASTI</a><a href="#dasar-hukum">{{ $en ? 'Legal Basis' : 'Dasar Hukum' }}</a><a href="#petugas">{{ $en ? 'Our People' : 'Petugas' }}</a></div></nav>

<section class="section" id="sejarah"><div class="container profile-story-grid"><div><span class="eyebrow">{{ $en ? 'Our journey' : 'Perjalanan kami' }}</span><h2>{{ $en ? 'Growing from one roof into one integrated gateway' : 'Tumbuh dari satu atap menjadi satu pintu' }}</h2><p>{{ $en ? 'ULT Unpad was established in 2015 using a “one roof” service model in a modest room, supported by representatives assigned from different work units.' : 'Unit Layanan Terpadu (ULT) Unpad didirikan pada tahun 2015 dengan sistem pelayanan “Satu Atap”. Pada masa awal, layanan dilaksanakan dalam satu ruangan sederhana oleh perwakilan dari tiap unit kerja yang ditugaskan di ULT.' }}</p><p>{{ $en ? 'In line with Unpad’s institutional quality strategy and Continuing Quality Improvement principles, ULT continues to remove service barriers across work units.' : 'Selaras dengan rencana strategis Unpad untuk meningkatkan kualitas kelembagaan dan prinsip Peningkatan Mutu Berkelanjutan, ULT terus dikembangkan untuk memotong hambatan pelayanan antarsatuan kerja.' }}</p></div><img src="{{ asset('images/profil-ult-loket.jpeg') }}" alt="Ruang loket pelayanan ULT Unpad"></div>
<div class="container timeline">
    <article><span>2015</span><div><h3>{{ $en ? 'One Roof Service' : 'Pelayanan Satu Atap' }}</h3><p>{{ $en ? 'Service representatives from multiple work units served users together in one location.' : 'Perwakilan berbagai unit kerja melayani pengguna bersama-sama dalam satu lokasi.' }}</p></div></article>
    <article><span>22.08<br>2016</span><div><h3>{{ $en ? 'Transformation into One Stop Service' : 'Transformasi Menjadi Satu Pintu' }}</h3><p>{{ $en ? 'ULT transformed into an integrated “one stop service”, managing requests from submission through completion in one place.' : 'ULT bertransformasi menjadi layanan “Satu Pintu”, dengan proses pengelolaan permohonan hingga penyelesaian dilakukan dalam satu tempat.' }}</p></div></article>
    <article><span>{{ $en ? 'Now' : 'Kini' }}</span><div><h3>{{ $en ? 'Hybrid & Inclusive Service' : 'Layanan Hybrid dan Inklusif' }}</h3><p>{{ $en ? 'ULT combines in-person and online service while continuing to strengthen disability-friendly access.' : 'ULT menggabungkan pelayanan luring dan daring serta terus memperkuat pelayanan yang ramah disabilitas.' }}</p></div></article>
</div></section>

<section class="section profile-purpose" id="visi-misi"><div class="container"><div class="section-head light"><div><span class="eyebrow">{{ $en ? 'Our direction' : 'Arah pelayanan' }}</span><h2>{{ $en ? 'Vision and mission' : 'Visi dan misi' }}</h2></div></div><div class="purpose-grid"><article class="vision-card"><span>01</span><h3>{{ $en ? 'Vision' : 'Visi' }}</h3><p>{{ $en ? 'To realize professional, accountable, simple, transparent, and informative public information services at Universitas Padjadjaran, fulfilling the public’s right to information in accordance with applicable laws.' : 'Terwujudnya pelayanan informasi publik di Universitas Padjadjaran yang profesional, akuntabel, simpel, transparan, dan informatif untuk memenuhi hak pemohon informasi publik sesuai ketentuan peraturan perundang-undangan.' }}</p></article><article class="mission-card"><span>02</span><h3>{{ $en ? 'Mission' : 'Misi' }}</h3><ol><li>{{ $en ? 'Provide fast, timely, simple, and high-quality public services.' : 'Menyediakan pengelolaan dan pelayanan publik yang cepat, tepat waktu, sederhana, dan berkualitas.' }}</li><li>{{ $en ? 'Develop effective and efficient technology-based information services.' : 'Membangun dan mengembangkan sistem pengelolaan dan layanan informasi yang efektif dan efisien berbasis teknologi informasi.' }}</li><li>{{ $en ? 'Improve governance quality through optimized one-stop public service.' : 'Meningkatkan kualitas penyelenggaraan pemerintahan melalui optimalisasi pengelolaan dan pelayanan publik satu pintu.' }}</li></ol></article></div></div></section>

<section class="section pasti-section" id="pasti"><div class="container"><div class="section-head"><div><span class="eyebrow">{{ $en ? 'Our motto' : 'Motto kami' }}</span><h2>Profesional, Akuntabel, Simpel, Transparan, Informatif.</h2></div></div><div class="pasti-grid">@foreach([['P','Profesional',$en?'Competent, responsive service.':'Pelayanan kompeten dan responsif.'],['A','Akuntabel',$en?'Responsible and measurable.':'Bertanggung jawab dan terukur.'],['S','Simpel',$en?'Easy-to-understand processes.':'Proses yang mudah dipahami.'],['T','Transparan',$en?'Clear requirements and procedures.':'Syarat dan prosedur yang jelas.'],['I','Informatif',$en?'Useful, relevant information.':'Informasi yang relevan dan berguna.']] as $value)<article><b>{{ $value[0] }}</b><h3>{{ $value[1] }}</h3><p>{{ $value[2] }}</p></article>@endforeach</div></div></section>

<section class="section legal-section" id="dasar-hukum"><div class="container legal-grid"><div><span class="eyebrow">{{ $en ? 'Accountable service' : 'Pelayanan yang akuntabel' }}</span><h2>{{ $en ? 'Legal basis' : 'Dasar hukum' }}</h2><p>{{ $en ? 'Unpad established a legal foundation for the formation and management of ULT as part of its commitment to service-user satisfaction.' : 'Sebagai komitmen terhadap pendirian dan pemenuhan kepuasan pengguna layanan, Unpad menetapkan landasan hukum untuk pembentukan dan pengelolaan ULT.' }}</p></div><div class="legal-list"><details open><summary>Peraturan Rektor No. 1 Tahun 2020 <span>+</span></summary><p>Tentang Susunan Organisasi dan Tata Kelola Universitas Padjadjaran.</p></details><details><summary>Keputusan Rektor No. 1289/UN6,RKT/Kep/HK/2016 <span>+</span></summary><p>Tentang Pembentukan Unit Layanan Terpadu Universitas Padjadjaran.</p></details><details><summary>Keputusan Rektor No. 2086/UN6,RKT/Kep/HK/2017 <span>+</span></summary><p>Tentang Panduan Pengelolaan Unit Layanan Terpadu Universitas Padjadjaran.</p></details></div></div></section>

<section class="section team-section" id="petugas"><div class="container team-grid"><div class="team-photo"><img src="{{ asset('images/profil-ult-pelayanan.jpeg') }}" alt="Petugas ULT sedang memberikan pelayanan kepada mahasiswa"><span>{{ $en ? 'Service with empathy' : 'Melayani dengan empati' }}</span></div><div><span class="eyebrow">{{ $en ? 'Service officers' : 'Petugas penyelenggara' }}</span><h2>{{ $en ? 'Prepared to provide excellent service' : 'Disiapkan untuk memberi layanan prima' }}</h2><p>{{ $en ? 'ULT officers pass a rigorous selection process, including psychological assessment and internships across Universitas Padjadjaran directorates.' : 'Petugas Unit Layanan Terpadu Universitas Padjadjaran melalui proses seleksi yang ketat, termasuk asesmen psikotes dan pemagangan pada unit kerja di berbagai direktorat.' }}</p><p>{{ $en ? 'They receive service-excellence competencies through regular training, enabling ULT to remain a reliable front line for lecturers, staff, students, and the public.' : 'Para petugas dibekali kompetensi layanan prima melalui pelatihan berkala agar ULT dapat menjadi garda terdepan yang andal bagi dosen, tenaga kependidikan, mahasiswa, dan masyarakat.' }}</p><a class="btn" href="{{ route('contact') }}">{{ $en ? 'Contact ULT' : 'Hubungi ULT' }}</a></div></div></section>

<section class="profile-gallery"><div class="profile-gallery-track"><figure><img src="{{ asset('images/profil-ult-ruang.jpeg') }}" alt="Ruang tunggu ULT Unpad"><figcaption>{{ $en ? 'Comfortable service area' : 'Ruang layanan yang nyaman' }}</figcaption></figure><figure><img src="{{ asset('images/profil-ult-mahasiswa.jpeg') }}" alt="Mahasiswa di ruang ULT Unpad"><figcaption>{{ $en ? 'An inclusive public space' : 'Ruang publik yang inklusif' }}</figcaption></figure><figure><img src="{{ asset('images/profil-ult-resepsionis.jpeg') }}" alt="Resepsionis ULT Unpad"><figcaption>{{ $en ? 'A clear service gateway' : 'Pintu layanan yang jelas' }}</figcaption></figure></div></section>
@endsection
